.PHONY: clean All

All:
	@echo "----------Building project:[ Weak-Pointers - Debug ]----------"
	@cd "Weak-Pointers" && "$(MAKE)" -f  "Weak-Pointers.mk"
clean:
	@echo "----------Cleaning project:[ Weak-Pointers - Debug ]----------"
	@cd "Weak-Pointers" && "$(MAKE)" -f  "Weak-Pointers.mk" clean
