.PHONY: clean All

All:
	@echo "----------Building project:[ Challanege - Debug ]----------"
	@cd "Challanege" && "$(MAKE)" -f  "Challanege.mk"
clean:
	@echo "----------Cleaning project:[ Challanege - Debug ]----------"
	@cd "Challanege" && "$(MAKE)" -f  "Challanege.mk" clean
