.PHONY: clean All

All:
	@echo "----------Building project:[ Virtual-Function - Debug ]----------"
	@cd "Virtual-Function" && "$(MAKE)" -f  "Virtual-Function.mk"
clean:
	@echo "----------Cleaning project:[ Virtual-Function - Debug ]----------"
	@cd "Virtual-Function" && "$(MAKE)" -f  "Virtual-Function.mk" clean
