.PHONY: clean All

All:
	@echo "----------Building project:[ Base-Class-Reference - Debug ]----------"
	@cd "Base-Class-Reference" && "$(MAKE)" -f  "Base-Class-Reference.mk"
clean:
	@echo "----------Cleaning project:[ Base-Class-Reference - Debug ]----------"
	@cd "Base-Class-Reference" && "$(MAKE)" -f  "Base-Class-Reference.mk" clean
