.PHONY: clean All

All:
	@echo "----------Building project:[ Virtual-Destructors - Debug ]----------"
	@cd "Virtual-Destructors" && "$(MAKE)" -f  "Virtual-Destructors.mk"
clean:
	@echo "----------Cleaning project:[ Virtual-Destructors - Debug ]----------"
	@cd "Virtual-Destructors" && "$(MAKE)" -f  "Virtual-Destructors.mk" clean
