.PHONY: clean All

All:
	@echo "----------Building project:[ Deriving-Our-Firs-Class - Debug ]----------"
	@cd "Deriving-Our-Firs-Class" && "$(MAKE)" -f  "Deriving-Our-Firs-Class.mk"
clean:
	@echo "----------Cleaning project:[ Deriving-Our-Firs-Class - Debug ]----------"
	@cd "Deriving-Our-Firs-Class" && "$(MAKE)" -f  "Deriving-Our-Firs-Class.mk" clean
